// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHnPae9XaXXk9bhgracRcfbwMvoRRXwZA',
    appId: '1:306039496940:web:c2d537a660a6596210c5c9',
    messagingSenderId: '306039496940',
    projectId: 'classcomfort-1a224',
    authDomain: 'classcomfort-1a224.firebaseapp.com',
    storageBucket: 'classcomfort-1a224.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQmfM0-gUIAtdQCcFXTeGl-_x6U7Bnn0',
    appId: '1:306039496940:android:4a334c089814e30510c5c9',
    messagingSenderId: '306039496940',
    projectId: 'classcomfort-1a224',
    storageBucket: 'classcomfort-1a224.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHnPae9XaXXk9bhgracRcfbwMvoRRXwZA',
    appId: '1:306039496940:web:8c2c5a191f24ee5010c5c9',
    messagingSenderId: '306039496940',
    projectId: 'classcomfort-1a224',
    authDomain: 'classcomfort-1a224.firebaseapp.com',
    storageBucket: 'classcomfort-1a224.firebasestorage.app',
  );
}
